### ISSUE TITLE
errors on line 18

### ISSUE THREAD

**Issue by kenzoawa** [brianwarehime/nights_watch#2]
Hi There @brianwarehime 
Must say that this is a great tool! 

I have come across a problem on line 18 in logs where it says :

'accessKeyDetails': KeyError
Traceback (most recent call last):
File "/var/task/main.py", line 18, in lambda_handler
event_principal = (event['detail']['resource']['accessKeyDetails']['principalId'])
KeyError: 'accessKeyDetails'

And the GuardDuty event isn't posted on slack channel and the monitoring on the lambda trows an error.

The notification i have got in GuardDuty is : 
UnauthorizedAccess:EC2

If you can shed some light, that would be great.
Thanks.

**Comment by kenzoawa** [comment]
When you comment out those lines - Lambda will execute okay. 

My guess is that in the json output that GD produces there is no field with event_principal.

**Comment by brianwarehime** [comment]
Hey, I totally forgot to update that before zipping it up. Just pushed a fix for this. Thanks!
